# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sprinkle"
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vladimir Malyarevich"]
  s.date = "2012-02-09"
  s.description = "Custom fork of sprinkle written by crafterm (crafterm@redartisan.com)"
  s.email = "vladimir.low@gmail.com"
  s.executables = ["sprinkle"]
  s.extra_rdoc_files = [
    "README.markdown",
    "TODO"
  ]
  s.files = `git ls-files -- lib/*`.split("\n") 
  s.homepage = "http://github.com/vladimir-low/sprinkle"
  s.require_paths = ["lib"]
  s.rubyforge_project = "sprinkle"
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby DSL based software provisioning tool"

  s.add_development_dependency(%q<rspec>, [">= 2.5"])
  s.add_runtime_dependency(%q<activesupport>, [">= 3.1.1"])
  s.add_runtime_dependency(%q<highline>, [">= 1.6.2"])
  s.add_runtime_dependency(%q<net-ssh>, [">= 2.2.1"])
  s.add_runtime_dependency(%q<net-ssh-gateway>, [">= 1.1.0"])
  s.add_runtime_dependency(%q<net-scp>, [">= 1.0.4"])
  s.add_runtime_dependency(%q<capistrano>, [">= 2.9.0"])
  
end
